app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
location:
    resource: app.media.location_controller
    type: rest
popular:
    resource: app.media.popular_controller
    type: rest
